import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import React from "react";
import styled from "styled-components";

const AuthLayout = ({ pageTitle, progress, hasBo, children }) => {
  return (
    <AuthLayoutStyles>
      <Head>
        <title>{pageTitle} - bidsloth</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <div className="top-holder">
          <div className="logo">
            <Link href="/">
              <Image
                src="https://res.cloudinary.com/dfmz4mxod/image/upload/v1688404666/mvp/red-bo_jv3es6.png"
                className="trademark-bo"
                width="60"
                height="60"
                alt="bidsloth"
              />
              <Image
                src="/trademark.png"
                className="trademark"
                width="75"
                height="75"
                alt="bidsloth"
              />
            </Link>
          </div>
          {progress && (
            <div className={hasBo ? "progress prog-with-bo" : "progress"}>
              {progress}
            </div>
          )}
        </div>
        <div className={hasBo ? "outlet has-bo" : "outlet"}>
          <div className="children">{children}</div>

          {hasBo && (
            <div className="has-bo-img">
              <Image
                src="/default-bo.png"
                width="300"
                height="370"
                alt="bidsloth"
              />
            </div>
          )}
        </div>
      </main>
    </AuthLayoutStyles>
  );
};

export default AuthLayout;

const AuthLayoutStyles = styled.div`
  width: 100vw;
  height: 100vh;
  overflow: hidden;
  padding: 0 6%;

  .logo {
    display: flex;
    align-items: center;
    margin-bottom: 2rem;
    a {
      display: inline-block;
      width: auto;
    }
  }

  .outlet {
    width: 400px;
    height: 100%;
    margin: auto;
    padding-top: 4%;

    &.has-bo {
      display: flex;
      align-items: center;
      width: 700px;
      justify-content: space-between;
      margin-top: 3rem;

      .children {
        width: 350px;
      }

      .has-bo-img {
        width: 280px;

        img {
          width: 100%;
        }
      }
    }
  }

  .auth-title {
    margin-bottom: 2rem;

    h1 {
      font-size: 1.8rem;
    }

    .smaller {
      font-size: 1.3rem;
    }

    p {
      font-size: 12px;
      margin-top: 10px;
    }
  }

  .cta {
    width: 100%;
    display: flex;
    align-items: center;
    justify-content: space-between;
    margin: auto;
    margin-top: 2.5rem;
    width: 75%;

    button {
      margin: 0;
      filter: drop-shadow(0px 4px 0px var(--black-color));
    }
  }

  .form {
    position: relative;
  }

  p {
    font-size: 14px;

    span {
      color: var(--primary-color);
      cursor: pointer;
      font-weight: 600;
      position: relative;
      transition: all 0.3s ease-in-out;
      &:hover {
        text-decoration: underline;
      }
    }
  }

  @media screen and (min-width: 1440px) {
    width: 100vw;
    max-width: 1290px;
    margin: auto;
    padding: 0;
    overflow-x: hidden;
    position: relative;
  }

  @media screen and (max-width: 850px) {
    .outlet {
      &.has-bo {
        display: block;
        width: 450px;
        margin: auto;
        margin-top: 4rem;

        .children {
          width: 100%;
        }

        .has-bo-img {
          display: none;
        }
      }
    }
  }

  @media screen and (max-width: 600px) {
    padding: 7%;

    .outlet {
      width: 100%;
      height: 100%;
      margin: auto;
      margin-top: 2rem;
      min-height: 500px !important;
      &.has-bo {
        width: 100%;
      }
    }

    .logo {
      display: block;
      position: relative;

      a {
        display: flex;
        align-items: center;
        justify-content: center;
        padding-bottom: 2rem;
        flex-direction: column;
      }

      .trademark {
        bottom: 15%;
      }
    }

    .progress {
      margin-left: 0;
      margin-top: 2rem;
    }
  }
`;
