name: deploy_production

on:
    push:
        branches: ["production"]
    pull_request:
        branches: ["production"]
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3
            - name: copy files to server
              uses: garygrossgarten/github-action-scp@v0.8.0
              with:
                  local: /home/runner/work/bidsloth-mvp/bidsloth-mvp
                  remote: production/frontend/
                  host: 3.78.67.147
                  username: ubuntu
                  password: AWSdanDoo216Doo
            - name: restart account service
              uses: appleboy/ssh-action@v0.1.5
              with:
                  host: 3.78.67.147
                  port: 22
                  username: ubuntu
                  password: AWSdanDoo216Doo
                  script: |
                      cd ./production/frontend/
                      npm install --legacy-peer-deps
                      pm2 restart frontend-production
